//
// Created by why-iskra on 02.06.2024.
//

#pragma once

#include <morphine/limits.h>

#define PARSER_LIMIT_STACK_CONTEXTS   262144
#define PARSER_LIMIT_STACK_ELEMENTS   262144
#define PARSER_STACK_EXPANSION_FACTOR 16

#define VISITOR_LIMIT_STACK_CONTEXTS   262144
#define VISITOR_LIMIT_STACK_FUNCTIONS  262144
#define VISITOR_STACK_EXPANSION_FACTOR 16

#define CODEGEN_LIMIT_STACK_INSTRUCTIONS MLIMIT_ARGUMENT_MAX
#define CODEGEN_LIMIT_STACK_VARIABLES    MLIMIT_ARGUMENT_MAX
#define CODEGEN_LIMIT_STACK_ANCHORS      MLIMIT_ARGUMENT_MAX
#define CODEGEN_LIMIT_STACK_CONSTANTS    MLIMIT_ARGUMENT_MAX
#define CODEGEN_LIMIT_STACK_CLOSURES     MLIMIT_ARGUMENT_MAX
#define CODEGEN_LIMIT_STACK_SCOPES       512
#define CODEGEN_LIMIT_STACK_TEMPORARY    2048
#define CODEGEN_STACK_EXPANSION_FACTOR   16
#define CODEGEN_TEMPORARY_LIMIT          512
