import argparse

parser = argparse.ArgumentParser(prog='Walker')
parser.add_argument('-s', '--source', default='')
parser.add_argument('-f', '--files', default='')
parser.add_argument('-p', '--prefix', default='')
parser.add_argument('-o', '--output', default=True)
args = parser.parse_args()

files = args.files.split(":")

if args.output == "":
    print("Empty output", file=sys.stderr)
    exit(1)

f = open(args.output, "w")
f.write("""//
// Generated by data.py
//

#pragma once

#include <stddef.h>

""")

for file in files:
    of = open(args.source + '/' + file, "rb")
    content = of.read()
    of.close()

    hex_content = ""
    for i in content:
        hex_content += hex(i) + ", "

    name = file.removeprefix(args.prefix) \
        .split(".")[0] \
        .replace("/", "_") \
        .replace("\\", "_") \
        .removeprefix("_")

    f.write("static const char " + name + "_data[] = { " + hex_content + " };\n")
    f.write("static const size_t " + name + "_size = " + str(len(content)) + ";\n")

f.close()
