//
// Created by why-iskra on 11.09.2024.
//

predef_word(true)
predef_word(false)
predef_word(env)
predef_word(nil)
predef_word(val)
predef_word(var)
predef_word(and)
predef_word(or)
predef_word(not)
predef_word(fun)
predef_word(if)
predef_word(else)
predef_word(while)
predef_word(do)
predef_word(for)
predef_word(break)
predef_word(continue)
predef_word(return)
predef_word(leave)
predef_word(typeof)
predef_word(lenof)
predef_word(yield)
predef_word(pass)
